### ISSUE TITLE
Screen Not displaying correctly on 0.2.6a (SDR Play version)

### ISSUE THREAD

**Issue by Paul-Nuneaton** [cjcliffe/CubicSDR#855] opened 2020-10-07 21:47 UTC
<img width="1440" alt="Screenshot 2020-10-07 at 22 36 08" src="https://user-images.githubusercontent.com/72527711/95391192-8ca82300-08ee-11eb-804e-05b567d0f304.png">
<img width="1440" alt="Screenshot 2020-10-07 at 22 35 26" src="https://user-images.githubusercontent.com/72527711/95391207-93369a80-08ee-11eb-94dc-0563ca247876.png">
I have uploaded two screen shots of two different versions running on the same Mac. 0.2.4 looks perfect and the other, 0.2.6a is messed up.

To select anything I need to point and click where it should be, not where it actually is now.

These shots are from the internal Macbook screen. When I plug in my HDMI 4K monitor, the 0.2.6a version looks normal.

I am running Big Sur on a 2019 4 port Macbook Pro

**Comment by FotisGR** [comment] 2020-10-09 11:46
Exactly the same problem here on my macbook pro 2018's screen (all resolutions tested) with Catalina 10.15.7. 
Version 0.2.5 its without this problem

**Comment by Dantali0n** [comment] 2020-10-09 12:17
This is a duplicate of https://github.com/cjcliffe/CubicSDR/issues/727 please continue the discussion there. In addition, please test patch https://github.com/cjcliffe/CubicSDR/pull/769 if you have time as it solves this issue.

@vsonnier could you close this for me?

**Comment by vsonnier** [comment] 2020-10-09 12:19
Thanks @Dantali0n for your support ! Let's close this indeed.

**Closed by vsonnier** 2020-10-09 12:19 UTC
