### ISSUE TITLE
Layout on OSX Catalina

### ISSUE THREAD

**Issue by robhardt** [cjcliffe/CubicSDR#845] opened 2020-08-31 00:54 UTC
All of the spectrum displays & the waterfall appear to be scaled down to 1/4 the size of their enclosing panels.  See the attached screenshot.  I've tried multiple combos of CubicSDR and wxWidget versions with the same results.  I'm just getting started with the codebase.  Any guidance as to where I can start poking around?  Thanks!

<img width="1425" alt="Screen Shot 2020-08-30 at 5 50 36 PM" src="https://user-images.githubusercontent.com/2475365/91673593-b600b280-eae9-11ea-863e-138224f331af.png">

**Comment by Dantali0n** [comment] 2020-08-31 08:29
This is a duplicate of https://github.com/cjcliffe/CubicSDR/issues/758 we have a merge request open on https://github.com/cjcliffe/CubicSDR/pull/769 you could give this patch a go to see if it resolves your issues.

**Comment by vsonnier** [comment] 2020-08-31 16:26
Thanks @Dantali0n indeed it is a duplicate of #758. Please @robhardt continue the discussion there.

**Closed by vsonnier** 2020-08-31 16:26 UTC
