### ISSUE TITLE
Aliasing in spectrum and spectrogram views

### ISSUE THREAD

**Issue by AlessandroDumas** [cjcliffe/CubicSDR#896] opened 2021-05-31 18:53 UTC
Sometimes, but repeatedly, depending on zoom, unexpected "stations" do appear, and disappear, where they should not. Them are not demodulated in any case; only graphics are affected. You may see them zooming in and out trough the frequency scale. Also the little detail window shows this behaviour, but on its own rules and range settings.

The issue goes off zooming totally out, in the whole converted spectrum.

I suspect that specturm is aliased / folded by the software (post acqusition). Probably also a masking like effect exists, if demodulating where nothing is seen.

A device aliasing can be excluded, because no settings are changing during the test.

---
Could someone spot the code part where this fft / zoom is done? I would like to try, but not sure can help.
Thanks.

sw: CubicSDR v0.2.6a - compiled on linux 4.9.40-rt30 - Ubuntu 18.04
hw converter: SDRPlay RSPdx

**Comment by vsonnier** [comment] 2021-09-24 06:03
Duplicate of #590, please find information there. The short answer is, this is a limitation of the FFT in the mainWaterfall.

**Closed by vsonnier** 2021-09-24 06:03 UTC
Labels: duplicate
