### ISSUE TITLE
Mac OS Big Sur, UX issues

### ISSUE THREAD

**Issue by mondospaceman** [cjcliffe/CubicSDR#918] opened 2021-10-02 19:50 UTC
![CubicSDR Startup](https://user-images.githubusercontent.com/78000554/135730043-c6e3099c-c5e0-4068-8ba1-3f1ac7584b3d.jpg)
New RSPduo, running on Big Sur.  UX comes up wonky.  Since I'm a new user (but experienced developer), I don't know what to attempt to fix this.

**Comment by guineapigsoup2** [comment] 2021-10-19 12:41
got the same issue using Mac OS Big Sur 11.6, with cubicSDR 2.6.3a and API 3.07

**Comment by vsonnier** [comment] 2021-11-13 09:46
Duplicate of #727.

**Closed by vsonnier** 2021-11-13 09:46 UTC
