### ISSUE TITLE
Option to Disable Visual Features?

### ISSUE THREAD

**Issue by ehidle** [cjcliffe/CubicSDR#721] opened 2019-03-29 12:40 UTC
Hi. I was wondering if there could be an option to disable all visual features (waterfalls, audio scope, etc) to make CubicSDR more friendly for use over remote desktop connections, and to reduce CPU load to an absolute minimum? 

It would also be nice to simply be able to say "hey give me a USB receiver at 3.573 MHz and just dump the audio" for unattended use cases. 

I looked in the manual and didn't see anything like this, so thought I would ask.

Thanks to all who work on this program!

EDIT: I found the options in CMakeLists.txt to disable the demodulator spectrum and sound scope, but didn't see anything about disabling the main waterfall...

**Comment by vsonnier** [comment] 2019-03-31 08:07
This is a duplicate of #577, please see @cjcliffe statement there.

**Closed by vsonnier** 2019-03-31 08:07 UTC

**Comment by ehidle** [comment] 2019-03-31 10:37
Hi guys, I wasn't really asking about running without a UI like these other two, but that would certainly be nice. I guess if I were to be very specific, all I'm asking for is maybe an additional option in CMake to disable the main spectrum scope and waterfall. In fact I think my ideal UI setup would be just to keep the demod waterfall turned on and turn off the audio waveform and main spectrum/waterfall. 

Anyway, just wanted to clarify that.

That said, it would be REALLY cool to also be able to launch/run without a UI at all so I can run several instances with several SDRs without bogging down the machine with UI stuff. :-)

**Comment by starvald** [comment] 2019-03-31 11:49
perhaps checkout https://github.com/szpajder/RTLSDR-Airband
am and nfm with soapysdr support.
