### ISSUE TITLE
AppImage mising for latest version

### ISSUE THREAD

**Issue by BuddyButterfly** [cjcliffe/CubicSDR#579] opened 2017-09-19 11:15 UTC
Hi,
first, tnx a lot for the great product. Latest AppImage seems to be missing for latest version. I found AppImage quite convenient. Will it be made available for download?

**Comment by vsonnier** [comment] 2017-09-19 11:48
This is a duplicate of #570. Please refer to this issue.

**Closed by vsonnier** 2017-09-19 11:48 UTC
Labels: duplicate

**Comment by BuddyButterfly** [comment] 2017-09-19 12:09
Sry, was  not aware of. Tnx!
