### ISSUE TITLE
Linux 0.2.3 - symbol lookup error: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0

### ISSUE THREAD

**Issue by hlfshell** [cjcliffe/CubicSDR#638] opened 2018-03-24 00:06 UTC
When launching freshly downloaded 0.2.3 in Ubuntu - 
```
me@computer:~/Downloads$ chmod +x CubicSDR-0.2.3-x86_64.AppImage 
me@computer:~/Downloads$ ./CubicSDR-0.2.3-x86_64.AppImage 
./CubicSDR-0.2.3-x86_64.AppImage: symbol lookup error: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined symbol: hb_font_funcs_set_variation_glyph_func
```
I do in fact have the latest `libpangoft2-1.0` via apt-get, and the location there does have the .so file referenced.

**Comment by vsonnier** [comment] 2018-03-24 05:54
This is a duplicate of #611, which already gathers issues on the AppImage. Please continue the discussion there, thanks !

**Closed by vsonnier** 2018-03-24 05:54 UTC
