### ISSUE TITLE
CubicSDR v0.2.6a slows down after running?

### ISSUE THREAD

**Issue by ebourlet** [cjcliffe/CubicSDR#936] opened 2021-12-29 23:20 UTC
I'm running HamPi on a Pi4 8GB . It came with CubicSDR v0.2.6a pre installed. 
I'm using it with an SDRPlay as a pan adapter on the IF of my IC-7100. It works great for a few hours then starts to slow down like there is a load on the resources. It doesn't matter if I set the CPU usage setting to High or Normal.  I can restart the program and it starts working fine again. Is there a setting I need to change? I'm not recording anything but it acts like there is a buffer somewhere that fills up and it starts to hang the program. I appreciate any help . I'm not a coder and am new to the pi platform.

**Comment by Dantali0n** [comment] 2021-12-30 10:24
Duplicate of #538

**Closed** 2023-01-13 18:42 UTC
Labels: duplicate, Raspberry Pi
