### ISSUE TITLE
v0.1.18-alpha crash OS X

### ISSUE THREAD

**Issue by effeerre75** [cjcliffe/CubicSDR#218] opened 2015-12-09 15:19 UTC
Error is "Segmentation fault: 11" if some modules are present in /usr/local/lib/SoapySDR/modules/
Works fine if the modules are removed.

**Comment by dc1rdb** [comment] 2015-12-09 15:35
Works fine here under 10.9.5 with the following modules (current build) present in /usr/local/lib/SoapySDR/modules/
libHackRFSupport.so
librtlsdrSupport.so
libsdrPlaySupport.so

**Comment by cjcliffe** [comment] 2015-12-09 22:46
Will investigate; likely an issue with an almost-compatible module with the same version attempting to load.

**Comment by effeerre75** [comment] 2015-12-10 15:07
Had some time to check the error is

SoapySDR::loadModule(/usr/local/lib/SoapySDR/modules/librtlsdrSupport.so)
  rtlsdr failed ABI check: Library ABI=0.4-2, Module ABI=0.3-0

Placing the modules that come inside the bundle in  /usr/local/lib/SoapySDR/modules/ 
CubicSDR start and works fine

Placing the module from /usr/local/lib/SoapySDR/modules/ in your bundle 
CubicSDR start but didn't works.

It think I had to make a clean install of my Soapy. If you want I'll wait for testing it ;)

**Comment by cjcliffe** [comment] 2016-01-09 05:44
Can't reproduce with anything but a compiled binary mismatch, this will improve with time as SoapySDR module versions stabilize so closing for now.

**Closed by cjcliffe** 2016-01-09 05:44 UTC
Labels: bug
