### ISSUE TITLE
Recording function doesn't work on Pi 4b

### ISSUE THREAD

**Issue by rrobinett** [cjcliffe/CubicSDR#869] opened 2021-01-14 14:13 UTC
Cubic V.0.2.5 installed via the Pi's 'add SW' feature is very fragile on the Pi, but it would be useful to me if it could record wav files.

However after setting the record path to '/home/pi' and pressing 'R', Cubic displays an error dialog: 
   "Recording path does not exist or is not writable"

V0.2.4 records perfectly on my Mac, but I cannot find that version prebuilt for the Pi

**Comment by vsonnier** [comment] 2021-02-08 17:00
Hi @rrobinett ,

>  '/home/pi' 

I would bet it is not writable then. Why not choosing another path ?

**Comment by vsonnier** [comment] 2021-02-08 17:02
Related to this wxWidgets bug, maybe : #823

**Comment by vsonnier** [comment] 2021-03-03 06:07
Closed, marked as duplicate of #823

**Closed by vsonnier** 2021-03-03 06:08 UTC
Labels: Linux, Raspberry Pi, bug
