### ISSUE TITLE
Odd Graphics Resolution Issue

### ISSUE THREAD

**Issue by wcravens** [cjcliffe/CubicSDR#811] opened 2020-04-12 19:06 UTC
Hello, I've just put Cubic on a new Ubuntu 18.04 installation for an RSPDuo.  It seems to be running fine but the graphics are oddly out of whack.  It seems that a lot of the renderings are half of what they should be.  And the mouse pointer is off too.  I'm including a screen-shot because it's hard to explain.

![Screenshot from 2020-04-12 14-02-42](https://user-images.githubusercontent.com/1262847/79077369-c04f1b00-7cc6-11ea-88d7-42cc72ab1942.png)

**Comment by Dantali0n** [comment] 2020-04-12 19:27
Seems related to https://github.com/cjcliffe/CubicSDR/pull/769

Do you happen to use display scaling as is typically done on 2k / 4k monitors?

**Comment by vsonnier** [comment] 2020-04-19 10:05
@Dantali0n  is right, it is a duplicate of #727.

**Closed by vsonnier** 2020-04-19 10:05 UTC
