### ISSUE TITLE
CubicSDR 0.2.6a Bad AM Demodulation

### ISSUE THREAD

**Issue by rusham55** [cjcliffe/CubicSDR#873] opened 2021-01-30 22:06 UTC
CubicSDR 0.2.6a AM demodulation produces heterodynes when station is not zerobeat.  While it is easy to tune AM broadcast stations to zerobeat it is impossible to do so on the AM aircraft band where about 50% transmissions are not zerobeat.  When this happens a loud heterodyne is produced on top of demodulated audio.  This is only for CubicSDR 0.2.6a.  Version 0.2.5 demodulates AM properly without heterodyning whether station is zerobeat or not.

**Comment by vsonnier** [comment] 2021-01-30 23:10
Duplicate of #796

**Closed by vsonnier** 2021-01-30 23:10 UTC
Labels: duplicate
