### ISSUE TITLE
Mouse issues with Cubic

### ISSUE THREAD

**Issue by Mojoron** [cjcliffe/CubicSDR#588] opened 2017-11-17 18:22 UTC
The last two updates have caused mouse/curser issues. When clicking on waterfall to change frequencies, the VFO does not change even using action keys. Scrolling is not there any longer either. I'm using an SDRplay, first generation, and cubicsdr 0.2.2 with the new SDR driver HPI/HW v 2.11 MacBook Air.

**Comment by dl2ymr** [comment] 2017-12-05 09:35
Here the same issue on my iMac with SDRplay first generation and cubicsdr 0.2.2.

**Comment by jcrippen** [comment] 2018-01-03 00:32
I had some mouse problems with 0.2.2 with macOS 10.12.6. But I switched to the master branch from GitHub using [homebrew-sdr from dholm](https://github.com/dholm/homebrew-sdr/blob/master/cubicsdr.rb) with the `--HEAD` option. Things work fine now; I also noticed some significant redraw speed increases. If you have Homebrew installed you might try this to see if your problems are already fixed for the next release.

**Comment by vsonnier** [comment] 2018-01-22 19:31
Binaries v0.23 for MacOS have been released. Please @Mojoron , @dl2ymr @jcrippen tell me how it runs for you.

**Comment by Mojoron** [comment] 2018-01-23 01:34
Now my Soapysdr doesn’t work and I’m not a programer to be able to do terminal work. Any work around for a new soapysdr for cubic?

mojoron

On Jan 22, 2018, at 1:31 PM, Vincent Sonnier <notifications@github.com> wrote:

Binaries v0.23 for MacOS have been released. Please @Mojoron <https://github.com/mojoron> , @dl2ymr <https://github.com/dl2ymr> @jcrippen <https://github.com/jcrippen> tell me how it runs for you.

**Comment by vsonnier** [comment] 2018-01-23 05:43
@Mojoron You don't have to build anything yourself, here https://github.com/cjcliffe/CubicSDR/releases/download/0.2.3/CubicSDR-0.2.3-Darwin.dmg is a standalone version for MacOS that gathers both CubicSDR and its lastest SoapySDR modules for communicating with the hardware.
For short, only install and run and it should be good.

**Comment by vsonnier** [comment] 2018-02-02 05:32
@Mojoron @dl2ymr @jcrippen Greetings all ! The Mac builds have been recently updated, so could you try
https://github.com/cjcliffe/CubicSDR/releases/download/0.2.3/CubicSDR-0.2.3-Darwin.dmg
and tell us if you still have issues or not, so we can close this issue. (or not).

**Comment by dl2ymr** [comment] 2018-02-04 11:49
Hi all,

thanks for your work, but the mouse issue is still here. Nothing changed.

Greetings and 73
Michael, DL2YMR

**Comment by TheButterZone** [comment] 2018-04-07 21:14
Same issue, OS, v0.2.3.

**Comment by cjcliffe** [comment] 2018-05-08 01:47
@dl2ymr @Mojoron @jcrippen -- Hi all, I still haven't reproduced the original issue here but I'm thinking with 0.2.4 now using wxWidgets 3.1.1 (which is used for mouse event handling and interaction) it might be worth trying again -- https://github.com/cjcliffe/CubicSDR/releases/tag/0.2.4

Please let me know if anything has gotten better or worse; thanks!

**Comment by dl2ymr** [comment] 2018-05-08 15:43
Hi,
can't start CubicSDR 0.2.4 because the SDRPlay is not found.

After downgrading to 0.2.3 everything is working fine. The Mouse Issue is gone and the SDRPlay is found without any problems.

Greetings and 73
Michael, DL2YMR

**Comment by vsonnier** [comment] 2018-05-27 05:47
@dl2ymr Hello ! SDRPlay has just released an updated API/DRIVER for Mac that should solve the SDRs detection problem (#649), could you give it a try with CubicSDR v0.24 ?

**Comment by dl2ymr** [comment] 2018-05-27 09:08
Hi Vincent,
tnx for your information.
Now it works!!!
Thank you guys for your work.
73 de
Michael, DL2YMR

**Comment by vsonnier** [comment] 2018-05-27 09:11
@dl2ymr Great ! Have fun with CubicSDR ! 
Let's close this issue then.

**Closed by vsonnier** 2018-05-27 09:11 UTC
Labels: bug
