### ISSUE TITLE
Installing CubicSDR on Pi4B

### ISSUE THREAD

**Issue by W9KJO** [cjcliffe/CubicSDR#803] opened 2020-04-04 13:38 UTC
When I run make I get

pi@raspberrypi4b1:~/Downloads/CubicSDR/build $ make
[  1%] Linking CXX executable x86/CubicSDR
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/demod/DemodulatorPreThread.cpp.o: in function `DemodulatorPreThread::setFrequency(long long)':
DemodulatorPreThread.cpp:(.text+0x7e8): undefined reference to `__atomic_store_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/demod/DemodulatorPreThread.cpp.o: in function `DemodulatorPreThread::getFrequency()':
DemodulatorPreThread.cpp:(.text+0x810): undefined reference to `__atomic_load_8'
/usr/bin/ld: DemodulatorPreThread.cpp:(.text+0x81c): undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/demod/DemodulatorPreThread.cpp.o: in function `DemodulatorPreThread::setSampleRate(long long)':
DemodulatorPreThread.cpp:(.text+0x844): undefined reference to `__atomic_store_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/demod/DemodulatorPreThread.cpp.o: in function `DemodulatorPreThread::getSampleRate()':
DemodulatorPreThread.cpp:(.text+0x86c): undefined reference to `__atomic_load_8'
/usr/bin/ld: DemodulatorPreThread.cpp:(.text+0x878): undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/demod/DemodulatorPreThread.cpp.o: in function `DemodulatorPreThread::run()':
DemodulatorPreThread.cpp:(.text+0x1f44): undefined reference to `__atomic_load_8'
/usr/bin/ld: DemodulatorPreThread.cpp:(.text+0x1f68): undefined reference to `__atomic_store_8'
/usr/bin/ld: DemodulatorPreThread.cpp:(.text+0x1f74): undefined reference to `__atomic_load_8'
/usr/bin/ld: DemodulatorPreThread.cpp:(.text+0x2040): undefined reference to `__atomic_load_8'
/usr/bin/ld: DemodulatorPreThread.cpp:(.text+0x205c): undefined reference to `__atomic_load_8'
/usr/bin/ld: DemodulatorPreThread.cpp:(.text+0x2098): undefined reference to `__atomic_load_8'
/usr/bin/ld: DemodulatorPreThread.cpp:(.text+0x2160): undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/demod/DemodulatorPreThread.cpp.o:DemodulatorPreThread.cpp:(.text+0x2af8): more undefined references to `__atomic_load_8' follow
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/demod/DemodulatorPreThread.cpp.o: in function `DemodulatorPreThread::run()':
DemodulatorPreThread.cpp:(.text+0x2e30): undefined reference to `__atomic_store_8'
/usr/bin/ld: DemodulatorPreThread.cpp:(.text+0x3aa4): undefined reference to `__atomic_store_8'
/usr/bin/ld: DemodulatorPreThread.cpp:(.text+0x3b50): undefined reference to `__atomic_load_8'
/usr/bin/ld: DemodulatorPreThread.cpp:(.text+0x3b64): undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/demod/DemodulatorPreThread.cpp.o: in function `DemodulatorPreThread::DemodulatorPreThread(DemodulatorInstance*)':
DemodulatorPreThread.cpp:(.text+0x4cb4): undefined reference to `__atomic_store_8'
/usr/bin/ld: DemodulatorPreThread.cpp:(.text+0x4cc8): undefined reference to `__atomic_store_8'
/usr/bin/ld: DemodulatorPreThread.cpp:(.text+0x4d0c): undefined reference to `__atomic_store_8'
/usr/bin/ld: DemodulatorPreThread.cpp:(.text+0x4d20): undefined reference to `__atomic_store_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/CubicSDR.cpp.o: in function `CubicSDR::setFrequency(long long)':
CubicSDR.cpp:(.text+0xdf4): undefined reference to `__atomic_load_8'
/usr/bin/ld: CubicSDR.cpp:(.text+0xe30): undefined reference to `__atomic_store_8'
/usr/bin/ld: CubicSDR.cpp:(.text+0xec8): undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/CubicSDR.cpp.o: in function `CubicSDR::getOffset()':
CubicSDR.cpp:(.text+0xef0): undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/CubicSDR.cpp.o: in function `CubicSDR::setOffset(long long)':
CubicSDR.cpp:(.text+0xf10): undefined reference to `__atomic_store_8'
/usr/bin/ld: CubicSDR.cpp:(.text+0xf44): undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/CubicSDR.cpp.o: in function `CubicSDR::getFrequency()':
CubicSDR.cpp:(.text+0x1030): undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/CubicSDR.cpp.o: in function `CubicSDR::lockFrequency(long long)':
CubicSDR.cpp:(.text+0x1064): undefined reference to `__atomic_store_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/CubicSDR.cpp.o: in function `CubicSDR::setSampleRate(long long)':
CubicSDR.cpp:(.text+0x1120): undefined reference to `__atomic_store_8'
/usr/bin/ld: CubicSDR.cpp:(.text+0x1148): undefined reference to `__atomic_load_8'
/usr/bin/ld: CubicSDR.cpp:(.text+0x1208): undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/CubicSDR.cpp.o: in function `CubicSDR::getSampleRate()':
CubicSDR.cpp:(.text+0x146c): undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/CubicSDR.cpp.o: in function `CubicSDR::setDevice(SDRDeviceInfo*, int)':
CubicSDR.cpp:(.text+0x3010): undefined reference to `__atomic_load_8'
/usr/bin/ld: CubicSDR.cpp:(.text+0x303c): undefined reference to `__atomic_store_8'
/usr/bin/ld: CubicSDR.cpp:(.text+0x304c): undefined reference to `__atomic_load_8'
/usr/bin/ld: CubicSDR.cpp:(.text+0x305c): undefined reference to `__atomic_load_8'
/usr/bin/ld: CubicSDR.cpp:(.text+0x3090): undefined reference to `__atomic_load_8'
/usr/bin/ld: CubicSDR.cpp:(.text+0x30b4): undefined reference to `__atomic_load_8'
/usr/bin/ld: CubicSDR.cpp:(.text+0x31cc): undefined reference to `__atomic_store_8'
/usr/bin/ld: CubicSDR.cpp:(.text+0x3208): undefined reference to `__atomic_store_8'
/usr/bin/ld: CubicSDR.cpp:(.text+0x3228): undefined reference to `__atomic_load_8'
/usr/bin/ld: CubicSDR.cpp:(.text+0x3250): undefined reference to `__atomic_store_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/CubicSDR.cpp.o: in function `CubicSDR::OnInit()':
CubicSDR.cpp:(.text+0x3bc0): undefined reference to `__atomic_store_8'
/usr/bin/ld: CubicSDR.cpp:(.text+0x3bd4): undefined reference to `__atomic_store_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/AppConfig.cpp.o: in function `DeviceConfig::DeviceConfig()':
AppConfig.cpp:(.text+0x864): undefined reference to `__atomic_store_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/AppConfig.cpp.o: in function `DeviceConfig::setOffset(long long)':
AppConfig.cpp:(.text+0x8c4): undefined reference to `__atomic_store_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/AppConfig.cpp.o: in function `DeviceConfig::getOffset()':
AppConfig.cpp:(.text+0x8d8): undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/AppConfig.cpp.o: in function `DeviceConfig::save(DataNode*)':
AppConfig.cpp:(.text+0xc14): undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/AppConfig.cpp.o: in function `AppConfig::setSnap(long long)':
AppConfig.cpp:(.text+0x12b4): undefined reference to `__atomic_store_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/AppConfig.cpp.o: in function `AppConfig::getSnap()':
AppConfig.cpp:(.text+0x12c8): undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/AppConfig.cpp.o: in function `AppConfig::setCenterFreq(long long)':
AppConfig.cpp:(.text+0x12e0): undefined reference to `__atomic_store_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/AppConfig.cpp.o: in function `AppConfig::getCenterFreq()':
AppConfig.cpp:(.text+0x12f4): undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/AppConfig.cpp.o: in function `AppConfig::save()':
AppConfig.cpp:(.text+0x3c3c): undefined reference to `__atomic_load_8'
/usr/bin/ld: AppConfig.cpp:(.text+0x3c80): undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/AppConfig.cpp.o: in function `AppConfig::AppConfig()':
AppConfig.cpp:(.text+0x4334): undefined reference to `__atomic_store_8'
/usr/bin/ld: AppConfig.cpp:(.text+0x4348): undefined reference to `__atomic_store_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/AppConfig.cpp.o: in function `DeviceConfig::load(DataNode*)':
AppConfig.cpp:(.text+0x57c0): undefined reference to `__atomic_store_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/AppConfig.cpp.o: in function `AppConfig::load()':
AppConfig.cpp:(.text+0x77b0): undefined reference to `__atomic_store_8'
/usr/bin/ld: AppConfig.cpp:(.text+0x77f4): undefined reference to `__atomic_store_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/sdr/SoapySDRThread.cpp.o:SoapySDRThread.cpp:(.text+0x340): more undefined references to `__atomic_store_8' follow
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/sdr/SoapySDRThread.cpp.o: in function `SDRThread::setFrequency(long long)':
SoapySDRThread.cpp:(.text+0x744): undefined reference to `__atomic_load_8'
/usr/bin/ld: SoapySDRThread.cpp:(.text+0x780): undefined reference to `__atomic_store_8'
/usr/bin/ld: SoapySDRThread.cpp:(.text+0x7a4): undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/sdr/SoapySDRThread.cpp.o: in function `SDRThread::getFrequency()':
SoapySDRThread.cpp:(.text+0x7cc): undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/sdr/SoapySDRThread.cpp.o: in function `SDRThread::lockFrequency(long long)':
SoapySDRThread.cpp:(.text+0x7f0): undefined reference to `__atomic_store_8'
/usr/bin/ld: SoapySDRThread.cpp:(.text+0x824): undefined reference to `__atomic_load_8'
/usr/bin/ld: SoapySDRThread.cpp:(.text+0x860): undefined reference to `__atomic_store_8'
/usr/bin/ld: SoapySDRThread.cpp:(.text+0x884): undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/sdr/SoapySDRThread.cpp.o: in function `SDRThread::setOffset(long long)':
SoapySDRThread.cpp:(.text+0x90c): undefined reference to `__atomic_store_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/sdr/SoapySDRThread.cpp.o: in function `SDRThread::getOffset()':
SoapySDRThread.cpp:(.text+0x958): undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/sdr/SoapySDRThread.cpp.o: in function `SDRThread::setSampleRate(long)':
SoapySDRThread.cpp:(.text+0xa78): undefined reference to `__atomic_store_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/sdr/SoapySDRThread.cpp.o: in function `SDRThread::getSampleRate()':
SoapySDRThread.cpp:(.text+0xac4): undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/sdr/SoapySDRThread.cpp.o: in function `SDRThread::readStream(std::shared_ptr<ThreadBlockingQueue<std::shared_ptr<SDRThreadIQData> > >)':
SoapySDRThread.cpp:(.text+0x1be8): undefined reference to `__atomic_load_8'
/usr/bin/ld: SoapySDRThread.cpp:(.text+0x1bfc): undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/sdr/SoapySDRThread.cpp.o: in function `SDRThread::updateSettings()':
SoapySDRThread.cpp:(.text+0x34ec): undefined reference to `__atomic_load_8'
/usr/bin/ld: SoapySDRThread.cpp:(.text+0x36ec): undefined reference to `__atomic_load_8'
/usr/bin/ld: SoapySDRThread.cpp:(.text+0x37b4): undefined reference to `__atomic_store_8'
/usr/bin/ld: SoapySDRThread.cpp:(.text+0x37c0): undefined reference to `__atomic_load_8'
/usr/bin/ld: SoapySDRThread.cpp:(.text+0x3828): undefined reference to `__atomic_load_8'
/usr/bin/ld: SoapySDRThread.cpp:(.text+0x39fc): undefined reference to `__atomic_load_8'
/usr/bin/ld: SoapySDRThread.cpp:(.text+0x3a14): undefined reference to `__atomic_load_8'
/usr/bin/ld: SoapySDRThread.cpp:(.text+0x3d78): undefined reference to `__atomic_load_8'
/usr/bin/ld: SoapySDRThread.cpp:(.text+0x3d90): undefined reference to `__atomic_store_8'
/usr/bin/ld: SoapySDRThread.cpp:(.text+0x3fa8): undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/CubicSDR.dir/src/sdr/SoapySDRThread.cpp.o: in function `SDRThread::init()':
SoapySDRThread.cpp:(.text+0x4410): undefined reference to `__atomic_store_8'
/usr/bin/ld: SoapySDRThread.cpp:(.text+0x4908): undefined reference to `__atomic_load_8'
/usr/bin/ld: SoapySDRThread.cpp:(.text+0x4aa4): undefined reference to `__atomic_load_8'
/usr/bin/ld: SoapySDRThread.cpp:(.text+0x4ab8): undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/CubicSDR.dir/build.make:1414: x86/CubicSDR] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/CubicSDR.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

I dont know what I need to do at this point.

Instructions Please.

Thanks you.

Walter

**Comment by vsonnier** [comment] 2020-04-04 13:50
Duplicate of #782 .

**Closed by vsonnier** 2020-04-04 13:50 UTC
