### ISSUE TITLE
Build Problem with CubicSDR CubicSDR-0.2.4

### ISSUE THREAD

**Issue by thosredfern** [cjcliffe/CubicSDR#751] opened 2019-09-06 18:55 UTC
I'm attempting a build CubicSDR-02.4 under Debian Stretch, 9.9.

I've built from a clean re-install of the source to insure that this isn't problem with some artifact of a previous build.

All the dependencies seem satisfied and  I believe I'm following the docs closely and I"m getting an error that I can't shake.

A search on the web brings up nothing.

Anyone else getting this error on a build from source?  Any ideas what the problem is here.
I'm pretty out of touch with C these days but his might be a problem with a header somewhere.

The offending line in the ModemAM.cpp file sure looks innocent enough.

CubicSDR-0.2.4/src/modules/modem/analog/ModemAM.cpp: In constructor ‘ModemAM::ModemAM()’:
CubicSDR-0.2.4/src/modules/modem/analog/ModemAM.cpp:7:63: error: cannot convert ‘double’ to ‘liquid_ampmodem_type’ for argument ‘2’ to ‘ampmodem_s* ampmodem_create(float, liquid_ampmodem_type, int)’
     demodAM = ampmodem_create(0.5, 0.0, LIQUID_AMPMODEM_DSB, 0);

Thank you for any assistance.

**Comment by vsonnier** [comment] 2019-09-06 19:24
Yet another duplicate of #749 and #746, please folow the advice there.

**Closed by vsonnier** 2019-09-06 19:24 UTC
