### ISSUE TITLE
New release? (58086c17f: ampmodem parameters have changed)

### ISSUE THREAD

**Issue by df7cb** [cjcliffe/CubicSDR#775] opened 2019-12-25 21:11 UTC
Hi,
I'm updating the liquid-dsp package in Debian, and the ampmodem change (https://github.com/jgaeddert/liquid-dsp/commit/22ccf5fb34a5a4253d984b2f1f81c67b7aa6eab7) makes the current CubicSDR release 0.2.5 incompatible. I see this is already fixed in master (58086c17f).
It would be nice to see a new CubicSDR release including this change.
Thanks!

**Comment by vsonnier** [comment] 2019-12-27 09:35
Duplicate of countless others, like #755. I leave it open though, as a friendly ping to @cjcliffe.

**Comment by df7cb** [comment] 2019-12-27 12:11
Thanks for the cross-links. I was looking for other issues, but couldn't find any with "release".

Fwiw, Debian is still on wxgtk 3.0 so even 0.2.5 won't build unless the 3.1 patch is reverted (which we do at the moment, https://salsa.debian.org/debian-hamradio-team/cubicsdr/blob/master/debian/patches/revert-migration-to-wx3.1), but putting up a new release seems to make sense in any case.

**Comment by vsonnier** [comment] 2023-01-13 20:49
Forgot to close this antique as duplicate.

**Closed** 2023-01-13 20:48 UTC
Labels: duplicate
