### ISSUE TITLE
OSX 0.2.6a User Interface Controls Issue

### ISSUE THREAD

**Issue by josepharmbruster** [cjcliffe/CubicSDR#857] opened 2020-10-30 21:48 UTC
I just updated from 0.2.4 to 0.2.6a on macOS Catalina 10.15.7, because 0.2.4 did not appear to recognize my new SDR Duo.  After installing 0.2.6a, it recognizes my duo, however... the window controls are all appearing mis-sized.  See the attached:

<img width="2305" alt="Screen Shot 2020-10-30 at 5 44 31 PM" src="https://user-images.githubusercontent.com/1966922/97759687-ea87ef00-1ad7-11eb-84c3-fb92da800ffc.png">

**Comment by Dantali0n** [comment] 2020-10-31 05:57
This is a duplicate of #727 please continue the discussion there. In addition, please test patch #769 if you have time as it solves this issue.

**Comment by vsonnier** [comment] 2021-08-02 13:06
#769 has been merged, which should fix the problem.

**Closed by vsonnier** 2021-08-02 13:06 UTC
