### ISSUE TITLE
Crash of  on remote device use

### ISSUE THREAD

**Issue by 9a4db** [cjcliffe/CubicSDR#776] opened 2019-12-26 19:16 UTC
Any advice please?
Cubic is able to see Lime on network,
on selection of remote device Cubic crash!?

// Terminal on Ubuntu PC side:
q@q-X756UX:~/Dev/CubicSDR/build/x64$ ./CubicSDR
Loading:: configuration file '/home/q/.CubicSDR/config.xml'

Audio Device #0 PulseAudio
	Default Output? Yes
	Default Input? Yes
	Input channels: 2
	Output channels: 2
	Duplex channels: 2
	Native formats:
		16-bit signed integer.
		32-bit signed integer.
		32-bit float normalized between plus/minus 1.0.
	Supported sample rates:
		8000hz
		16000hz
		22050hz
		32000hz
		44100hz
		48000hz
		96000hz

SDR enumerator starting.
SoapySDR init..
	API Version: v0.6.0
	ABI Version: v0.6
	Install root: /usr/local
	Loading modules... 
linux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_003.010.002.000-3-g122bfae1

	Available factories...lime, null, remote, sdrplay, uhd
Available vertical sync SwapInterval functions: 
	glxSwapIntervalEXT: No
	DRI2SwapInterval: No
	glxSwapIntervalMESA: No
	glxSwapIntervalSGI: No
No vertical sync swap interval functions available.
Loaded font 'Bitstream Vera Sans Mono' from '/usr/local/share/cubicsdr/fonts/vera_sans_mono12_0.png', parsed 255 characters.
Loaded font 'Bitstream Vera Sans Mono' from '/usr/local/share/cubicsdr/fonts/vera_sans_mono16_0.png', parsed 255 characters.
Loaded font 'Bitstream Vera Sans Mono' from '/usr/local/share/cubicsdr/fonts/vera_sans_mono18_0.png', parsed 255 characters.
Loaded font 'Bitstream Vera Sans Mono' from '/usr/local/share/cubicsdr/fonts/vera_sans_mono24_0.png', parsed 255 characters.
Loaded font 'Bitstream Vera Sans Mono' from '/usr/local/share/cubicsdr/fonts/vera_sans_mono27_0.png', parsed 255 characters.
Loaded font 'Bitstream Vera Sans Mono' from '/usr/local/share/cubicsdr/fonts/vera_sans_mono32_0.png', parsed 255 characters.
Loaded font 'Bitstream Vera Sans Mono' from '/usr/local/share/cubicsdr/fonts/vera_sans_mono36_0.png', parsed 255 characters.
  addr = 24607:1027
  driver = remote
  label = LimeNET-Micro [USB 2.0] 58399D024CE9
  media = USB 2.0
  module = FT601
  name = LimeNET-Micro
  remote = tcp://192.168.10.106:55132
  remote:driver = lime
  serial = 0058399D024CE9
Make device 0
[INFO] Make connection: 'LimeNET-Micro [USB 2.0] 58399D024CE9'
[INFO] Reference clock 30.72 MHz
[INFO] Device name: LimeNET-Micro
[INFO] Reference: 30.72 MHz
[INFO] LMS7002M register cache: Disabled
  boardSerialNumber=0x9d024ce9
  firmwareVersion=6
  gatewareVersion=1.0
  hardwareVersion=19
  protocolVersion=1
  remote:version=0.5.2-g6d9bd820

Reporting enumeration complete.
SDR enumerator done.
[INFO] Make connection: 'LimeNET-Micro [USB 2.0] 58399D024CE9'
[INFO] Reference clock 30.72 MHz
[INFO] Device name: LimeNET-Micro
[INFO] Reference: 30.72 MHz
[INFO] LMS7002M register cache: Disabled
Terminating SDR thread..
ERROR: thread '9SDRThread' has not terminated in time ! (> 3000 ms)
![Screenshot from 2019-12-26 20-04-11](https://user-images.githubusercontent.com/30326618/71487514-08cbf100-281c-11ea-8392-5b5b43fcf629.png)

// after crash, testing remote device
q@q-X756UX:~/Dev/CubicSDR/build/x64$ SoapySDRUtil --find="192.168.10.106=raspberrypi-2, driver=remote"
######################################################
######################################################

linux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_003.010.002.000-3-g122bfae1

Found device 0
  addr = 24607:1027
  driver = remote
  label = LimeNET-Micro [USB 2.0] 58399D024CE9
  media = USB 2.0
  module = FT601
  name = LimeNET-Micro
  remote = tcp://192.168.10.106:55132
  remote:driver = lime
  serial = 0058399D024CE9

q@q-X756UX:~/Dev/CubicSDR/build/x64$ 

// Terminal on Raspberry PI side

pi@raspberrypi:~ $ SoapySDRServer --bind
######################################################
######################################################

Server version: 0.5.2-g6d9bd820
Server UUID: ad9235f5-0142-15e4-8567-7a34007f0101
Launching the server... tcp://[::]:55132
Server bound to [::]:55132
Launching discovery server... 
Connecting to DNS-SD daemon... 
[INFO] Avahi version:  avahi 0.7
[INFO] Avahi hostname: raspberrypi-2
[INFO] Avahi domain:   local
[INFO] Avahi FQDN:     raspberrypi-2.local
[INFO] avahi_entry_group_add_service(raspberrypi-2._soapy._tcp)
Press Ctrl+C to stop the server
SoapyServerListener::accept([::ffff:192.168.10.197]:36154)
SoapyServerListener::accept([::ffff:192.168.10.197]:36156)
SoapyServerListener::close()
SoapyServerListener::close()
SoapyServerListener::accept([::ffff:192.168.10.197]:36160)
SoapyServerListener::accept([::ffff:192.168.10.197]:36164)
SoapyServerListener::accept([::ffff:192.168.10.197]:36166)
SoapyServerListener::close()
SoapyServerListener::close()
SoapyServerListener::accept([::ffff:192.168.10.197]:36168)
SoapyServerListener::close()
SoapyServerListener::close()
SoapyServerListener::accept([::ffff:192.168.10.197]:36172)
SoapyServerListener::accept([::ffff:192.168.10.197]:36174)
SoapyServerListener::accept([::ffff:192.168.10.197]:36176)
SoapyServerListener::close()
SoapyServerListener::close()
SoapyServerListener::accept([::ffff:192.168.10.197]:36178)
SoapyServerListener::close()
SoapyServerListener::handlerLoop() FAIL: SoapyRPCUnpacker::recv(header) FAIL: 
SoapyServerListener::close()

// after crash, testing remote device
SoapyServerListener::accept([::ffff:192.168.10.197]:36226)
SoapyServerListener::accept([::ffff:192.168.10.197]:36228)
SoapyServerListener::close()
SoapyServerListener::close()

**Comment by vsonnier** [comment] 2019-12-26 19:55
Duplicate of https://github.com/pothosware/SoapyRemote/issues/75, continue discussion there.

**Closed by vsonnier** 2019-12-26 19:55 UTC
